language: java
jdk:
- oraclejdk8
branches:
  only:
  - develop
notifications:
  email:
    recipients:
    - cedar-core-developers@lists.stanford.edu
    on_success: never
    on_failure: always
install: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=false clean deploy --settings .m2/travis-settings.xml'
script: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=true clean --settings .m2/travis-settings.xml'
env:
  global:
  - secure: iqIt8+7oWvwSYCFcRcC8oeto+1TMzgujd5c+PhrUB0n0AE741ywKkxNQXmvwPeO44SGraQaWROykqUYYtyxyWD5+Ep+HEPn4f99IYtx6MyEJIj2ceA6OmVpophxrm7E8ZLjfV9pZCSxGa9QkxaWDnkIfC1mbo7HzBiSvMPQQ8C6nB6ys9qmJzZ9+p9tCb8kcexsrEcAJCb8sGEBb/NvhZiASuzL7L8frQ0NTXGD02hhMe8FBstwiwoYRzImoCN/sxHlRaYNCe5BdIWC2a23rWsj0y4tL0taLKXMTbn+ejwTQXR9rtBvWXslZ4EfSD9M+SiLp49esj6P5fg6IsShMYjoILLzYLqHacU1DP80zxK7qET915a06cPLsKOvMiaZh2XbsS0BaaRtwl00B9fg6A3gGQ8Qu+h2PT0RzkIWGBJBd34D2kaN8Gyhz07hC7KYjiQ92h6S520K+QiAEe7QeJLCG1bJxfz7O4GoHT8QA1tDV/Is+Zd9InncPJnuaXqW7qRys4adNMziweyqKD7czEJgkrPjOnsdsZdP4evwnjSKGz0A7jfaOcljvXpTC346dGuLicW+ie9Z4pTraySXf5jyeRqVtAlsNy5YZ7jAJ2kXyMKs6KNt74cJyKnjQR+/UjeUy75lVaydzxnOtBweMYPyZwkzPSK8AqXO6qktrwCM=
  - secure: P7U0FhuMARRQy2D+T//nrM3kCEuB3RdFChfFk+eaJ5q6m31QLvo/vvYETq7hCfYQjvhOSxOs8JhaDX7jeHRPShZRKEL9OteRS1nM7tXWOMlQb0BBcvCBJqlfPSAQrtb27T9LJR11u2VE//C2WeSJZhgFAm6fLHK1PKjStamgBdq4nIk9WIGCpSf6woYUFEQlvA1gvWH4OF7YHqqbBcHSdAxWh5IPkJqD4ka7jzev5jgvjpfBb+BxHv7HxjNZt5Sh7RLgrWUfuExgkqTtHE97rA6+gqAIpNeXM5wViw4V+GOw0gB5qt7cfevICojRRvM0b2a4OeryPj+lX+UWGq2IA5/8MGESqdarqFyULX1zlOogVTa+BjnBjT2uCqoNtM8oWbX2jCz6VqmaymEGQtt15sSptbGwM4F9VlRwjeBERCPF8qFS0qkGZo6p911RkfCwOAnx/A1pknsR2H/QJyalV1jWwBhQ8/+UFnRA2UtYM/LU/0xlfMMUWU9ZppwT/hNJav/+tyXius+D78JkX8SRI11ZFteuscaAGGMDkpih/ecsaGdaea+n8qSJCpji1KM+xKOSB8G0bc2YNPwvEXCc9qEafzdqF45adzHAiNKrGpyeYNXzne24VUADjuPa3B3VMsygc4E55i9K/zaCT0Mu/zaMaiQFDyc1wN1piZxC0yo=
